package uk.gov.moj.cpp.hearing.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;
import java.util.Arrays;
import uk.gov.moj.cpp.hearing.command.api.accescontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;
global uk.gov.moj.cpp.accesscontrol.hearing.providers.HearingProvider hearingProvider;

rule "Command - API - Action - hearing.initiate"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.initiate");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Probation Admin", "Listing Officers", "Court Clerks", "Legal Advisers", "Court Administrators", "Crown Court Admin", "System Users","Court Associate", "Magistrates"))
   || eval(userAndGroupProvider.hasPermission($action, RuleConstants.expectedPermissionsForCase()));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-prosecution-counsel")
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Advocates", "Non CPS Prosecutors", "Defence Lawyers", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-defendants-welsh-translations"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-defendants-welsh-translations");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers","Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-prosecution-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-prosecution-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers","Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-draft-result");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-draft-result-v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-draft-result-v2");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.delete-draft-result-v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.delete-draft-result-v2");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-multiple-draft-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-multiple-draft-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-days-draft-result"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-days-draft-result");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-days-draft-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-days-draft-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers","Defence Users","Advocates","Court Associate", "Defence Lawyers", "Court Administrators", "Non CPS Prosecutors"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-defence-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-defence-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.share-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.share-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.share-results-v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.share-results-v2");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.amend"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.amend");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.amend-for-support"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.amend-for-support");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Second Line Support"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.share-days-results"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.share-days-results");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end


rule "Command - API - Action - hearing.create-hearing-event-definitions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.create-hearing-event-definitions");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "System Users", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.log-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.log-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-witness"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-witness");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-hearing-events"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-hearing-events");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.correct-hearing-event"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.correct-hearing-event");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-plea"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-plea");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-verdict"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-verdict");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.generate-nows"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.generate-nows");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-nows-material-status"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-nows-material-status");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.delete-attendee"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.delete-attendee");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.upload-subscriptions"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.upload-subscriptions");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "System Users", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-defendant-attendance-on-hearing-day"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-defendant-attendance-on-hearing-day");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-hearing-case-note"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-hearing-case-note");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.save-application-response"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.save-application-response");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-respondent-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-respondent-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-applicant-counsel"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-applicant-counsel");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-company-representative"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-company-representative");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-interpreter-intermediary");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-interpreter-intermediary");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-interpreter-intermediary"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-interpreter-intermediary");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.set-trial-type"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.set-trial-type");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Deputies", "DJMC", "Judge", "Recorders", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end
rule "Command - API - Action - hearing.publish-court-list"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.publish-court-list");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end
rule "Command - API - Action - hearing.publish-hearing-lists-for-crown-courts"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.publish-hearing-lists-for-crown-courts");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.publish-hearing-lists-for-crown-courts-with-ids"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.publish-hearing-lists-for-crown-courts-with-ids");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.record-session-time"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.record-session-time");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators", "Crown Court Admin"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.book-provisional-hearing-slots"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.book-provisional-hearing-slots");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Associate", "Legal Advisers", "Court Clerks", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-targets"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-targets");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action -  hearing.change-hearing-detail"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.change-hearing-detail");
   eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action -  hearing.correct-hearing-days-without-court-centre"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.correct-hearing-days-without-court-centre");
   eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.request-approval"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.request-approval");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Associate", "Legal Advisers", "Court Clerks", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end


rule "Command - API - Action - hearing.validate-result-amendments"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.validate-result-amendments");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Court Associate", "Legal Advisers", "Court Clerks", "Court Administrators")
        && hearingProvider.isUserAllowedToApproveResultAmendment($action)
   );
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.add-master-defendant-id-to-defendant"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.add-master-defendant-id-to-defendant");
   eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.mark-as-duplicate-v2"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.mark-as-duplicate-v2");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "System Users", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.mark-as-duplicate-with-reason"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.mark-as-duplicate-with-reason");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "System Users", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.mark-as-duplicate"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.mark-as-duplicate");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "System Users"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.update-resultline-shared-dates"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-resultline-shared-dates");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.reusable-info"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.reusable-info");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Judiciary", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.youth-court-defendants"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.youth-court-defendants");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end
rule "Command - API - Action - hearing.change-cancel-amendments"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.change-cancel-amendments");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end


rule "Command - API - Action - hearing.update-related-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.update-related-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Crown Court Admin", "Court Administrators", "Legal Advisers", "Court Clerks", "System Users", "Court Associate"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.remove-offences-from-existing-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.remove-offences-from-existing-hearing");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, "Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.unlock-hearing"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.unlock-hearing");
   eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action,"Listing Officers", "Court Clerks", "Legal Advisers", "Court Associate", "Court Administrators", "Crown Court Admin"));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.delete-hearing-bdf"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.delete-hearing-bdf");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end

rule "Command - API - Action - hearing.patch-application-finalised-on-target"
  when
    $outcome: Outcome();
    $action: Action(name == "hearing.patch-application-finalised-on-target");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end
