#%RAML 0.8
title: Hearing Command handler
baseUri:  message://command/handler/message/hearing

/hearing.handler.command:
  post:
      body:
# Initiate Hearing
        application/vnd.hearing.initiate+json:
            example: !include json/hearing.initiate.json
            schema:  !include json/schema/hearing.initiate.json

        application/vnd.hearing.command.extend-hearing+json:
            example: !include json/hearing.command.extend-hearing.json
            schema:  !include json/schema/hearing.command.extend-hearing.json

        application/vnd.hearing.command.update-related-hearing+json:
            example: !include json/hearing.command.update-related-hearing.json
            schema:  !include json/schema/hearing.command.update-related-hearing.json

        application/vnd.hearing.command.register-hearing-against-offence+json:
            schema: !include json/schema/hearing.command.register-hearing-against-offence.json
            example: !include json/hearing.command.register-hearing-against-offence.json

        application/vnd.hearing.command.register-hearing-against-offence-v2+json:
            schema: !include json/schema/hearing.command.register-hearing-against-offence-v2.json
            example: !include json/hearing.command.register-hearing-against-offence-v2.json

        application/vnd.hearing.command.register-hearing-against-defendant+json:
            schema: !include json/schema/hearing.command.register-hearing-against-defendant.json
            example: !include json/hearing.command.register-hearing-against-defendant.json


        application/vnd.hearing.command.register-hearing-against-case+json:
            schema: !include json/schema/hearing.command.register-hearing-against-case.json
            example: !include json/hearing.command.register-hearing-against-case.json

  # Hearing Rescheduled
        application/vnd.hearing.command.clear-vacated-trial+json:
            schema: !include json/schema/hearing.command.clear-vacated-trial.json
            example: !include json/hearing.command.clear-vacated-trial.json

  # Mark Hearing as Duplicate
        application/vnd.hearing.command.mark-as-duplicate+json:
            schema: !include json/schema/hearing.command.mark-as-duplicate.json
            example: !include json/hearing.command.mark-as-duplicate.json

        application/vnd.hearing.command.mark-as-duplicate-for-cases+json:
            schema: !include json/schema/hearing.command.mark-as-duplicate-for-cases.json
            example: !include json/hearing.command.mark-as-duplicate-for-cases.json

        application/vnd.hearing.command.mark-as-duplicate-for-defendants+json:
            schema: !include json/schema/hearing.command.mark-as-duplicate-for-defendants.json
            example: !include json/hearing.command.mark-as-duplicate-for-defendants.json

        application/vnd.hearing.command.mark-as-duplicate-for-offences+json:
            schema: !include json/schema/hearing.command.mark-as-duplicate-for-offences.json
            example: !include json/hearing.command.mark-as-duplicate-for-offences.json

# Log Event
        application/vnd.hearing.command.log-hearing-event+json:
            example: !include json/hearing.command.log-hearing-event.json
            schema: !include json/schema/hearing.command.log-hearing-event.json
        application/vnd.hearing.command.update-hearing-events+json:
            example: !include json/hearing.command.update-hearing-events.json
            schema: !include json/schema/hearing.command.update-hearing-events.json

        application/vnd.hearing.create-hearing-event-definitions+json:
            example: !include json/hearing.create-hearing-event-definitions.json
            schema:  !include json/schema/hearing.create-hearing-event-definitions.json

        application/vnd.hearing.command.correct-hearing-event+json:
            example: !include json/hearing.command.correct-hearing-event.json
            schema: !include json/schema/hearing.command.correct-hearing-event.json

# Prosecution Counsel
        application/vnd.hearing.command.add-prosecution-counsel+json:
            example: !include json/hearing.command.add-prosecution-counsel.json
            schema:  !include json/schema/hearing.command.add-prosecution-counsel.json
        application/vnd.hearing.command.remove-prosecution-counsel+json:
            example: !include json/hearing.command.remove-prosecution-counsel.json
            schema:  !include json/schema/hearing.command.remove-prosecution-counsel.json
        application/vnd.hearing.command.update-prosecution-counsel+json:
            example: !include json/hearing.command.update-prosecution-counsel.json
            schema:  !include json/schema/hearing.command.update-prosecution-counsel.json
        application/vnd.hearing.command.remove-case-from-group-cases+json:
            example: !include json/hearing.command.remove-case-from-group-cases.json
            schema: !include json/schema/hearing.command.remove-case-from-group-cases.json
        application/vnd.hearing.command.update-hearing-after-case-removed-from-group-cases+json:
            example: !include json/hearing.command.update-hearing-after-case-removed-from-group-cases.json
            schema: !include json/schema/hearing.command.update-hearing-after-case-removed-from-group-cases.json

# Defence Counsel
        application/vnd.hearing.command.add-defence-counsel+json:
            example: !include json/hearing.command.add-defence-counsel.json
            schema:  !include json/schema/hearing.command.add-defence-counsel.json
        application/vnd.hearing.command.remove-defence-counsel+json:
            example: !include json/hearing.command.remove-defence-counsel.json
            schema:  !include json/schema/hearing.command.remove-defence-counsel.json
        application/vnd.hearing.command.update-defence-counsel+json:
            example: !include json/hearing.command.update-defence-counsel.json
            schema:  !include json/schema/hearing.command.update-defence-counsel.json

# Results
        application/vnd.hearing.command.save-draft-result+json:
            example: !include json/hearing.command.save-draft-result.json
            schema: !include json/schema/hearing.command.save-draft-result.json
        application/vnd.hearing.command.save-multiple-draft-results+json:
            example: !include json/hearing.command.save-multiple-draft-results.json
            schema: !include json/schema/hearing.command.save-multiple-draft-results.json
        application/vnd.hearing.command.save-days-draft-result+json:
            example: !include json/hearing.command.save-days-draft-result.json
            schema:  !include json/schema/hearing.command.save-days-draft-result.json
        application/vnd.hearing.command.save-days-draft-results+json:
            example: !include json/hearing.command.save-days-draft-results.json
            schema:  !include json/schema/hearing.command.save-days-draft-results.json

        application/vnd.hearing.command.save-draft-result-v2+json:
            example: !include json/hearing.command.save-draft-result-v2.json
            schema: !include json/schema/hearing.command.save-draft-result-v2.json
        application/vnd.hearing.command.delete-draft-result-v2+json:
            example: !include json/hearing.command.delete-draft-result-v2.json
            schema: !include json/schema/hearing.command.delete-draft-result-v2.json

        application/vnd.hearing.command.share-results+json:
            example: !include json/hearing.command.share-results.json
            schema:  !include json/schema/hearing.command.share-results.json

        application/vnd.hearing.command.share-results-v2+json:
            example: !include json/hearing.command.share-results-v2.json
            schema:  !include json/schema/hearing.command.share-results-v2.json

        application/vnd.hearing.command.share-days-results+json:
            example: !include json/hearing.command.share-days-results.json
            schema:  !include json/schema/hearing.command.share-days-results.json

        application/vnd.hearing.command.remove-targets+json:
            example: !include json/hearing.command.remove-targets.json
            schema: !include json/schema/hearing.command.remove-targets.json

        application/vnd.hearing.command.add-master-defendant-id-to-defendant+json:
            example: !include json/hearing.command.add-master-defendant-id-to-defendant.json
            schema: !include json/schema/hearing.command.add-master-defendant-id-to-defendant.json

        application/vnd.hearing.command.update-result-lines-status+json:
            example: !include json/hearing.command.update-result-lines-status.json
            schema:  !include json/schema/hearing.command.update-result-lines-status.json

        application/vnd.hearing.command.update-days-result-lines-status+json:
            example: !include json/hearing.command.update-days-result-lines-status.json
            schema:  !include json/schema/hearing.command.update-days-result-lines-status.json





#Update Plea
        application/vnd.hearing.hearing-offence-plea-update+json:
            example: !include json/hearing.hearing-offence-plea-update.json
            schema:  !include json/schema/hearing.hearing-offence-plea-update.json

        application/vnd.hearing.command.update-plea-against-offence+json:
            schema: !include json/schema/hearing.command.update-plea-against-offence.json
            example: !include json/hearing.command.update-plea-against-offence.json

        application/vnd.hearing.command.enrich-update-plea-with-associated-hearings+json:
            schema: !include json/schema/hearing.command.enrich-update-plea-with-associated-hearings.json
            example: !include json/hearing.command.enrich-update-plea-with-associated-hearings.json

        application/vnd.hearing.command.enrich-associated-hearings-with-indicated-plea+json:
            schema: !include json/schema/hearing.command.enrich-associated-hearings-with-indicated-plea.json
            example: !include json/hearing.command.enrich-associated-hearings-with-indicated-plea.json

# Update Verdict
        application/vnd.hearing.command.update-verdict+json:
            example: !include json/hearing.command.update-verdict.json
            schema:  !include json/schema/hearing.command.update-verdict.json

        application/vnd.hearing.command.update-verdict-against-offence+json:
            example: !include json/hearing.command.update-verdict-against-offence.json
            schema:  !include json/schema/hearing.command.update-verdict-against-offence.json

        application/vnd.hearing.command.enrich-update-verdict-with-associated-hearings+json:
            example: !include json/hearing.command.enrich-update-verdict-with-associated-hearings.json
            schema:  !include json/schema/hearing.command.enrich-update-verdict-with-associated-hearings.json

# Update Defendant Attendance On Hearing Day
        application/vnd.hearing.update-defendant-attendance-on-hearing-day+json:
            example: !include json/hearing.update-defendant-attendance-on-hearing-day.json
            schema:  !include json/schema/hearing.update-defendant-attendance-on-hearing-day.json

# Sending Sheet Complete
        application/vnd.hearing.record-sending-sheet-complete+json:
            example: !include json/hearing.record-sending-sheet-complete.json
            schema:  !include json/schema/hearing.record-sending-sheet-complete.json

        application/vnd.hearing.record-mags-court-hearing+json:
            example: !include json/hearing.record-mags-court-hearing.json
            schema:  !include json/schema/hearing.record-mags-court-hearing.json

# Case Defendant Details Update
        application/vnd.hearing.update-case-defendant-details-against-hearing-aggregate+json:
            schema: !include json/schema/hearing.update-case-defendant-details-against-hearing-aggregate.json
            example: !include json/hearing.update-case-defendant-details-against-hearing-aggregate.json

        application/vnd.hearing.update-case-defendant-details+json:
            schema: !include json/schema/hearing.update-case-defendant-details.json
            example: !include json/hearing.update-case-defendant-details.json

# Application Organisation Details Update
        application/vnd.hearing.update-defence-organisation-for-application+json:
            schema: !include json/schema/hearing.update-defence-organisation-for-application.json
            example: !include json/hearing.update-defence-organisation-for-application.json

# Case Defendant Offences Update
        application/vnd.hearing.command.update-offences-for-defendant+json:
            schema: !include json/schema/hearing.command.update-offences-for-defendant.json
            example: !include json/hearing.command.update-offences-for-defendant.json

        application/vnd.hearing.command.add-new-offence-to-hearings+json:
            schema: !include json/schema/hearing.command.add-new-offence-to-hearings.json
            example: !include json/hearing.command.add-new-offence-to-hearings.json

        application/vnd.hearing.command.add-new-offence-to-hearings-v2+json:
            schema: !include json/schema/hearing.command.add-new-offence-to-hearings-v2.json
            example: !include json/hearing.command.add-new-offence-to-hearings-v2.json

        application/vnd.hearing.command.update-offence-on-hearings+json:
            schema: !include json/schema/hearing.command.update-offence-on-hearings.json
            example: !include json/hearing.command.update-offence-on-hearings.json

        application/vnd.hearing.command.update-offence-on-hearings-v2+json:
            schema: !include json/schema/hearing.command.update-offence-on-hearings-v2.json
            example: !include json/hearing.command.update-offence-on-hearings-v2.json

        application/vnd.hearing.command.delete-offence-on-hearings+json:
            schema: !include json/schema/hearing.command.delete-offence-on-hearings.json
            example: !include json/hearing.command.delete-offence-on-hearings.json

        application/vnd.hearing.command.delete-offence-on-hearings-v2+json:
            schema: !include json/schema/hearing.command.delete-offence-on-hearings-v2.json
            example: !include json/hearing.command.delete-offence-on-hearings-v2.json

# Hearing Detail Change
        application/vnd.hearing.change-hearing-detail+json:
                schema: !include json/schema/hearing.change-hearing-detail.json
                example: !include json/hearing.change-hearing-detail.json

# Hearing Detail Vacated Trial Change
        application/vnd.hearing.update-vacated-trial-detail+json:
                schema: !include json/schema/hearing.update-vacated-trial-detail.json
                example: !include json/hearing.update-vacated-trial-detail.json

# Hearing note
        application/vnd.hearing.command.save-hearing-case-note+json:
                schema: !include json/schema/hearing.command.save-hearing-case-note.json
                example: !include json/hearing.command.save-hearing-case-note.json

# notification upload subscriptions
        application/vnd.hearing.command.upload-subscriptions+json:
                schema: !include json/schema/hearing.command.upload-subscriptions.json
                example: !include json/hearing.command.upload-subscriptions.json

# Respondent Counsel
        application/vnd.hearing.command.add-respondent-counsel+json:
            example: !include json/hearing.command.add-respondent-counsel.json
            schema:  !include json/schema/hearing.command.add-respondent-counsel.json
        application/vnd.hearing.command.remove-respondent-counsel+json:
            example: !include json/hearing.command.remove-respondent-counsel.json
            schema:  !include json/schema/hearing.command.remove-respondent-counsel.json
        application/vnd.hearing.command.update-respondent-counsel+json:
            example: !include json/hearing.command.update-respondent-counsel.json
            schema:  !include json/schema/hearing.command.update-respondent-counsel.json

# Applicant Counsel
        application/vnd.hearing.command.add-applicant-counsel+json:
            example: !include json/hearing.command.add-applicant-counsel.json
            schema:  !include json/schema/hearing.command.add-applicant-counsel.json
        application/vnd.hearing.command.remove-applicant-counsel+json:
            example: !include json/hearing.command.remove-applicant-counsel.json
            schema:  !include json/schema/hearing.command.remove-applicant-counsel.json
        application/vnd.hearing.command.update-applicant-counsel+json:
            example: !include json/hearing.command.update-applicant-counsel.json
            schema:  !include json/schema/hearing.command.update-applicant-counsel.json

# Add Defendant
        application/vnd.hearing.add-defendants+json:
            example: !include json/hearing.add-defendants.json
            schema:  !include json/schema/hearing.add-defendants.json

# Add Defendant
        application/vnd.hearing.command.user-attached-to-judiciary+json:
            example: !include json/hearing.command.user-attached-to-judiciary.json
            schema:  !include json/schema/hearing.command.user-attached-to-judiciary.json

# Update Application Detail
        application/vnd.hearing.update-court-application+json:
            schema: !include json/schema/hearing.update-court-application.json
            example: !include json/hearing.update-court-application.json

# Update Application Detail
        application/vnd.hearing.update-laareference-for-application+json:
            schema: !include json/schema/hearing.update-laareference-for-application.json
            example: !include json/hearing.update-laareference-for-application.json

# Eject case or application
        application/vnd.hearing.command.eject-case-or-application+json:
            schema: !include json/schema/hearing.command.eject-case-or-application.json
            example: !include json/hearing.command.eject-case-or-application.json


# Company Representative
        application/vnd.hearing.command.add-company-representative+json:
            example: !include json/hearing.command.add-company-representative.json
            schema:  !include json/schema/hearing.command.add-company-representative.json
        application/vnd.hearing.command.update-company-representative+json:
            example: !include json/hearing.command.update-company-representative.json
            schema:  !include json/schema/hearing.command.update-company-representative.json
        application/vnd.hearing.command.remove-company-representative+json:
            example: !include json/hearing.command.remove-company-representative.json
            schema:  !include json/schema/hearing.command.remove-company-representative.json

# Interpreter Intermediary
        application/vnd.hearing.command.add-interpreter-intermediary+json:
            example: !include json/hearing.command.add-interpreter-intermediary.json
            schema:  !include json/schema/hearing.command.add-interpreter-intermediary.json
        application/vnd.hearing.command.update-interpreter-intermediary+json:
            example: !include json/hearing.command.update-interpreter-intermediary.json
            schema:  !include json/schema/hearing.command.update-interpreter-intermediary.json
        application/vnd.hearing.command.remove-interpreter-intermediary+json:
            example: !include json/hearing.command.remove-interpreter-intermediary.json
            schema:  !include json/schema/hearing.command.remove-interpreter-intermediary.json

# Set Trial Type
        application/vnd.hearing.command.set-trial-type+json:
            schema: !include json/schema/hearing.command.set-trial-type.json
            example: !include json/hearing.command.set-trial-type.json

#NCES Notification
        application/vnd.hearing.command.update-defendant-with-financial-order+json:
            schema: !include json/schema/hearing.command.update-defendant-with-financial-order.json
            example: !include json/hearing.command.update-defendant-with-financial-order.json
        application/vnd.hearing.command.update-defendant-with-application-details+json:
            schema: !include json/schema/hearing.command.update-defendant-with-application-details.json
            example: !include json/hearing.command.update-defendant-with-application-details.json

# Update offence results for a defendant
        application/vnd.hearing.command.handler.update-offence-results+json:
            schema: !include json/schema/hearing.command.handler.update-offence-results.json
            example: !include json/hearing.command.handler.update-offence-results.json

# Update Case Markers
        application/vnd.hearing.command.update-case-markers+json:
              schema: !include json/schema/hearing.command.update-case-markers.json
              example: !include json/hearing.command.update-case-markers.json
        application/vnd.hearing.command.update-case-markers-with-associated-hearings+json:
              schema: !include json/schema/hearing.command.update-case-markers-with-associated-hearings.json
              example: !include json/hearing.command.update-case-markers-with-associated-hearings.json

# Update Prosecutor
        application/vnd.hearing.command.update-cps-prosecutor-with-associated-hearings+json:
              schema: !include json/schema/hearing.command.update-cps-prosecutor-with-associated-hearings.json
              example: !include json/hearing.command.update-cps-prosecutor-with-associated-hearings.json

# Defendant Legal Aid Status Updated
        application/vnd.hearing.command.update-defendant-legalaid-status+json:
            schema: !include json/schema/hearing.command.update-defendant-legalaid-status.json
            example: !include json/hearing.command.update-defendant-legalaid-status.json

# Defendant Legal Aid Status Updated for Hearing
        application/vnd.hearing.command.update-defendant-legalaid-status-for-hearing+json:
            schema: !include json/schema/hearing.command.update-defendant-legalaid-status-for-hearing.json
            example: !include json/hearing.command.update-defendant-legalaid-status-for-hearing.json

# Hearing Resulted Case  Updated
        application/vnd.hearing.command.update-case-defendants+json:
            schema: !include json/schema/hearing.command.update-case-defendants.json
            example: !include json/hearing.command.update-case-defendants.json

# Hearing Resulted Application  Updated
        application/vnd.hearing.command.update-application-defendants+json:
            schema: !include json/schema/hearing.command.update-application-defendants.json
            example: !include json/hearing.command.update-application-defendants.json

# Case  Defendants Updated for Hearing
        application/vnd.hearing.command.update-case-defendants-for-hearing+json:
            schema: !include json/schema/hearing.command.update-case-defendants-for-hearing.json
            example: !include json/hearing.command.update-case-defendants-for-hearing.json

# Application  Defendants Updated for Hearing
        application/vnd.hearing.command.update-application-defendants-for-hearing+json:
            schema: !include json/schema/hearing.command.update-application-defendants-for-hearing.json
            example: !include json/hearing.command.update-application-defendants-for-hearing.json

#  Export court list to exhibit
        application/vnd.hearing.command.record-court-list-export-successful+json:
            schema: !include json/schema/hearing.command.record-court-list-export-successful.json
            example: !include json/hearing.command.record-court-list-export-successful.json

        application/vnd.hearing.command.record-court-list-export-failed+json:
            schema: !include json/schema/hearing.command.record-court-list-export-failed.json
            example: !include json/hearing.command.record-court-list-export-failed.json

        application/vnd.hearing.command.publish-court-list+json:
            schema: !include json/schema/hearing.command.publish-court-list.json
            example: !include json/hearing.command.publish-court-list.json

        application/vnd.hearing.command.publish-hearing-lists-for-crown-courts+json:
            schema: !include json/schema/hearing.command.publish-hearing-lists-for-crown-courts.json
            example: !include json/hearing.command.publish-hearing-lists-for-crown-courts.json

        application/vnd.hearing.command.publish-hearing-lists-for-crown-courts-with-ids+json:
            schema: !include json/schema/hearing.command.publish-hearing-lists-for-crown-courts-with-ids.json
            example: !include json/hearing.command.publish-hearing-lists-for-crown-courts-with-ids.json

        application/vnd.hearing.command.record-session-time+json:
            schema: !include json/schema/hearing.command.record-session-time.json
            example: !include json/hearing.command.record-session-time.json

#  Book provisional slots for hearing
        application/vnd.hearing.command.book-provisional-hearing-slots+json:
            schema: !include json/schema/hearing.command.book-provisional-hearing-slots.json
            example: !include json/hearing.command.book-provisional-hearing-slots.json

# Update Hearing days
        application/vnd.hearing.command.cancel-hearing-days+json:
            schema: !include json/schema/hearing.command.cancel-hearing-days.json
            example: !include json/hearing.command.cancel-hearing-days.json
#  Correct hearing days without court centre id
        application/vnd.hearing.command.correct-hearing-days-without-court-centre+json:
            schema: !include json/schema/hearing.command.correct-hearing-days-without-court-centre.json
            example: !include json/hearing.command.correct-hearing-days-without-court-centre.json

        application/vnd.hearing.command.request-approval+json:
            schema: !include json/schema/hearing.command.request-approval.json
            example: !include json/hearing.command.request-approval.json

        application/vnd.hearing.command.validate-result-amendments+json:
            schema: !include json/schema/hearing.command.validate-result-amendments.json
            example: !include json/hearing.command.validate-result-amendments.json

#  Amend hearing
        application/vnd.hearing.command.change-cancel-amendments+json:
            schema: !include json/schema/hearing.command.change-cancel-amendments.json
            example: !include json/hearing.command.change-cancel-amendments.json

        application/vnd.hearing.command.update-resultline-shared-dates+json:
            schema: !include json/schema/hearing.command.update-resultline-shared-dates.json
            example: !include json/hearing.command.update-resultline-shared-dates.json

# Reuse Of Information

        application/vnd.hearing.command.reusable-info+json:
            schema: !include json/schema/hearing.command.reusable-info.json
            example: !include json/hearing.command.reusable-info.json

# Youth court defendants

        application/vnd.hearing.command.youth-court-defendants+json:
            schema: !include json/schema/hearing.command.youth-court-defendants.json
            example: !include json/hearing.command.youth-court-defendants.json

# Delete Hearing
        application/vnd.hearing.command.delete-hearing+json:
            schema: !include json/schema/hearing.command.delete-hearing.json
            example: !include json/hearing.command.delete-hearing.json

        application/vnd.hearing.command.delete-hearing-for-prosecution-cases+json:
            schema: !include json/schema/hearing.command.delete-hearing-for-prosecution-cases.json
            example: !include json/hearing.command.delete-hearing-for-prosecution-cases.json

        application/vnd.hearing.command.delete-hearing-for-defendants+json:
            schema: !include json/schema/hearing.command.delete-hearing-for-defendants.json
            example: !include json/hearing.command.delete-hearing-for-defendants.json

        application/vnd.hearing.command.delete-hearing-for-offences+json:
            schema: !include json/schema/hearing.command.delete-hearing-for-offences.json
            example: !include json/hearing.command.delete-hearing-for-offences.json

        application/vnd.hearing.command.delete-hearing-for-court-applications+json:
            schema: !include json/schema/hearing.command.delete-hearing-for-court-applications.json
            example: !include json/hearing.command.delete-hearing-for-court-applications.json

        application/vnd.hearing.command.delete-hearing-bdf+json:
          schema: !include json/schema/hearing.command.delete-hearing-bdf.json
          example: !include json/hearing.command.delete-hearing-bdf.json
# Unallocate Hearing
        application/vnd.hearing.command.unallocate-hearing+json:
            schema: !include json/schema/hearing.command.unallocate-hearing.json
            example: !include json/hearing.command.unallocate-hearing.json

        application/vnd.hearing.command.remove-hearing-for-prosecution-cases+json:
            schema: !include json/schema/hearing.command.remove-hearing-for-prosecution-cases.json
            example: !include json/hearing.command.remove-hearing-for-prosecution-cases.json

        application/vnd.hearing.command.remove-hearing-for-defendants+json:
            schema: !include json/schema/hearing.command.remove-hearing-for-defendants.json
            example: !include json/hearing.command.remove-hearing-for-defendants.json

        application/vnd.hearing.command.remove-hearing-for-offences+json:
            schema: !include json/schema/hearing.command.remove-hearing-for-offences.json
            example: !include json/hearing.command.remove-hearing-for-offences.json

# Record Next Hearing Day Updated
        application/vnd.hearing.command.record-next-hearing-day-updated+json:
            schema: !include json/schema/hearing.command.record-next-hearing-day-updated.json
            example: !include json/hearing.command.record-next-hearing-day-updated.json

# Remove Offences From Existing Hearing
        application/vnd.hearing.command.remove-offences-from-existing-hearing+json:
            schema: !include json/schema/hearing.command.remove-offences-from-existing-hearing.json
            example: !include json/hearing.command.remove-offences-from-existing-hearing.json

        application/vnd.hearing.command.remove-offences-from-existing-allocated-hearing+json:
          schema: !include json/schema/hearing.command.remove-offences-from-existing-allocated-hearing.json
          example: !include json/hearing.command.remove-offences-from-existing-allocated-hearing.json

        application/vnd.hearing.command.amend+json:
            schema: !include json/schema/hearing.command.amend.json
            example: !include json/hearing.command.amend.json

        application/vnd.hearing.command.amend-for-support+json:
            schema: !include json/schema/hearing.command.amend.json
            example: !include json/hearing.command.amend.json


# Extend Custody Time Limit
        application/vnd.hearing.command.extend-custody-time-limit+json:
            schema: !include json/schema/hearing.command.extend-custody-time-limit.json
            example: !include json/hearing.command.extend-custody-time-limit.json

# Stop Custody Time Limit
        application/vnd.hearing.command.stop-custody-time-limit-clock+json:
             schema: !include json/schema/hearing.command.stop-custody-time-limit-clock.json
             example: !include json/hearing.command.stop-custody-time-limit-clock.json



# Court restrictions
        application/vnd.hearing.command.restrict-court-list+json:
            schema: !include json/schema/hearing.command.court-list-restricted.json
            example: !include json/hearing.command.court-list-restricted.json

# Welsh defendant translations
        application/vnd.hearing.command.save-defendants-welsh-translations+json:
            schema: !include json/schema/hearing.command.save-defendants-welsh-translations.json
            example: !include json/hearing.command.save-defendants-welsh-translations.json

# Unlock Hearing
        application/vnd.hearing.command.unlock-hearing+json:
          schema: !include json/schema/hearing.command.unlock-hearing.json
          example: !include json/hearing.command.unlock-hearing.json

# Unlock Hearing
        application/vnd.hearing.command.replicate-results+json:
          schema: !include json/schema/hearing.command.replicate-results.json
          example: !include json/hearing.command.replicate-results.json

# Unlock Hearing
        application/vnd.hearing.command.add-witness+json:
          schema: !include json/schema/hearing.command.add-witness.json
          example: !include json/hearing.command.add-witness.json


# Breach Applications to be added
        application/vnd.hearing.command.breach-applications-to-be-added+json:
            schema: !include json/schema/hearing.command.breach-applications-to-be-added.json
            example: !include json/hearing.command.breach-applications-to-be-added.json

        application/vnd.hearing.command.delete-court-application-hearing+json:
            schema: !include json/schema/hearing.command.delete-court-application-hearing.json
            example: !include json/hearing.command.delete-court-application-hearing.json

# patch for ha_target
        application/vnd.hearing.command.patch-application-finalised-on-target+json:
            schema: !include json/schema/hearing.command.patch-application-finalised-on-target.json
            example: !include json/hearing.command.patch-application-finalised-on-target.json

